### ISSUE TITLE
deleting all files from repos doesn't allow re-using the repos

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/credential-status-manager-git#15]
If I delete all files in my two status repos, I'd expect the credential-status-manager to re-initialize the repos on restart, but it doesn't because of how the manager checks to see if the repo is empty: it looks for an empty result on a call to the octokit getContent method:

https://github.com/digitalcredentials/credential-status-manager-git/blob/076921b76c5475e1d35b6f0ffb6fb71883b92bf4/src/credential-status-manager-github.ts#L184-L188

And, for whatever reason, after the repos have had files - even though they've been deleted - the getContent call doesn't return an empty result.

Could there be some other way to confirm the repos are empty, or at least empty enough that they can be used? So, for example, checking for the existence of the log.json and config.json files.

Alternatively, we could update the README to make clear to people that the repos have to be brand new and that simply deleting all contents isn't sufficient.

**Comment by alexfigtree** [comment]
Close; won't fix
